name: Build

on:
  push:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        version: [ 7.4, 7.4-zts ]

    runs-on: ubuntu-latest
    container:
      image: php:${{ matrix.version }}

    steps:
    - uses: actions/checkout@v3

    - name: php-config
      id: php_config
      run: echo "::set-output name=EXTENSION_DIR::$(php-config --extension-dir)"

    - name: phpize
      run: phpize .
      working-directory: ./extension

    - name: configure
      run: ./configure
      working-directory: ./extension

    - name: make
      run: make
      working-directory: ./extension

    - name: install
      run: make install
      working-directory: ./extension

    - name: upload
      uses: actions/upload-artifact@v3.0.0
      with:
        path: ${{ steps.php_config.outputs.EXTENSION_DIR }}/xhprof.so
