name: Build

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: php:7.4

    steps:
    - uses: actions/checkout@v3

    - name: phpize
      run: phpize .
      working-directory: ./extension

    - name: configure
      run: ./configure
      working-directory: ./extension

    - name: make
      run: make
      working-directory: ./extension

    - name: install
      run: make install
      working-directory: ./extension
