name: Build

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: install deps
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'

    - uses: actions/checkout@v3

    - name: phpize
      run: phpize .
      working-directory: ./extension

    - name: configure
      run: ./configure
      working-directory: ./extension

    - name: make
      run: make
      working-directory: ./extension

    - name: install
      run: sudo make install
      working-directory: ./extension
