name: Build

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: install deps
      run: sudo apt install -y php7.4-dev build-essential
    - uses: actions/checkout@v3
    - name: phpize
      run: phpize .
      working-directory: ./extension
    - name: configure
      run: ./configure
      working-directory: ./extension
    - name: make
      run: make && make install
      working-directory: ./extension
